version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
- package-ecosystem: gomod
  directory: "/supplier"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
- package-ecosystem: gomod
  directory: "/reactor"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/supplier"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/reactor"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/grafana"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/mq"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: rabbitmq
    update-types:
    - version-update:semver-major
    - version-update:semver-minor
