version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
- package-ecosystem: gomod
  directories:
  - "/grafana-export"
  - "/reactor"
  - "/supplier"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directories:
  - "/"
  - "/grafana"
  - "/grafana-export"
  - "/mq"
  - "/reactor"
  - "/supplier"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
