version: '3.8'

services:
  supplier:
    image: golang:1.15-buster
    command: bash -c 'go build -o /usr/bin && /usr/bin/supplier'
    working_dir: /usr/src/app
    environment:
      TZ: Asia/Tokyo
      MASTODON_USER_ID:
      MASTODON_ACCESS_TOKEN:
      MASTODON_SERVER_URL:
      MASTODON_STREAM: direct
      MQ_HOST: amqp://mq
      MQ_USERNAME: shiko
      MQ_PASSWORD: shiko
      REACTOR_HOST: reactor
      PORT: 80
    volumes:
      - ./supplier:/usr/src/app

  reactor:
    image: golang:1.15-buster
    command: bash -c 'go build -o /usr/bin && /usr/bin/reactor'
    working_dir: /usr/src/app
    environment:
      USER_ID: 1
      TZ: Asia/Tokyo
      DB_HOST: database
      DB_DATABASE: ejaculation
      DB_USERNAME: shiko
      DB_PASSWORD: shiko
      MASTODON_ACCESS_TOKEN:
      MASTODON_SERVER_URL:
      MQ_HOST: amqp://mq
      MQ_USERNAME: shiko
      MQ_PASSWORD: shiko
      PORT: 80
    volumes:
      - ./reactor:/usr/src/app

  web:
    image: nginx:1.18
    ports:
      - "${COUNTER_PORT-8080}:80"
    volumes:
      - ./public:/var/www/html
      - ./conf:/etc/nginx/conf.d

  grafana:
    image: grafana/grafana:7.1.5
    environment:
      TZ:
      GF_INSTALL_PLUGINS: neocat-cal-heatmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_SECURITY_ALLOW_EMBEDDING: 1
      GF_SERVER_SERVE_FROM_SUB_PATH: 1
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      GF_SERVER_DOMAIN: grafana
    volumes:
      - grafana:/var/lib/grafana

  mq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: shiko
      RABBITMQ_DEFAULT_PASS: shiko
    volumes:
      - mq:/var/lib/rabbitmq

  database:
    image: mysql:8.0
    command: [--character-set-server=utf8, --default-authentication-plugin=mysql_native_password]
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    environment:
      TZ:
      MYSQL_DATABASE: ejaculation
      MYSQL_USER: shiko
      MYSQL_PASSWORD: shiko
      MYSQL_ROOT_PASSWORD: shiko

volumes:
  grafana:
    driver: local
  mq:
    driver: local
  database:
    driver: local
