{
 "title": "ぴゅっぴゅカウンター",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  count AS \"time\",\n  count\nFROM counts\nWHERE\n  \"user\" = 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Contribution",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  count\nFROM counts\nWHERE\n  $__timeFilter(date) AND\n  \"user\" = 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Monthly Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\"count\") AS \"count\",\n  NOW() AS \"time\"\nFROM \"counts\"\nWHERE $__timeFilter(\"date\") AND \"user\" = 1\n"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  EXTRACT(EPOCH FROM \"date\") AS \"time\",\n  \"count\" AS \"value\"\nFROM \"counts\"\nWHERE $__timeFilter(\"date\")\nORDER BY \"date\" ASC\n"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"date\" AS \"time\",\n  \"count\"\nFROM \"counts\"\nWHERE\n  $__timeFilter(\"date\")\nORDER BY \"date\" DESC"
    }
   ]
  }
 ]
}