// Code generated by MockGen. DO NOT EDIT.
// Source: queue.go

// Package service is a generated GoMock package.
package service

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockQueueWriter is a mock of QueueWriter interface
type MockQueueWriter struct {
	ctrl     *gomock.Controller
	recorder *MockQueueWriterMockRecorder
}

// MockQueueWriterMockRecorder is the mock recorder for MockQueueWriter
type MockQueueWriterMockRecorder struct {
	mock *MockQueueWriter
}

// NewMockQueueWriter creates a new mock instance
func NewMockQueueWriter(ctrl *gomock.Controller) *MockQueueWriter {
	mock := &MockQueueWriter{ctrl: ctrl}
	mock.recorder = &MockQueueWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockQueueWriter) EXPECT() *MockQueueWriterMockRecorder {
	return m.recorder
}

// Publish mocks base method
func (m *MockQueueWriter) Publish(event Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish
func (mr *MockQueueWriterMockRecorder) Publish(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockQueueWriter)(nil).Publish), event)
}
