package hardcoding

import "github.com/chitoku-k/ejaculation-counter/reactor/repository"

var (
	DoubletVariants = []string{
		"-dom -- doom",
		"Egyptian -- gypsy",
		"abbreviate -- abridge",
		"abet -- bet",
		"absolve -- assoil",
		"acajou -- cashew",
		"achievement -- hatchment",
		"acute -- ague -- cute",
		"adamant -- diamond",
		"adjutant -- aid",
		"advantage -- vantage",
		"adventure -- venture",
		"advocate -- avouch -- avow",
		"affray -- fray",
		"aggravate -- aggrieve",
		"aim -- esteem -- estimate",
		"ait -- eyot",
		"alarm -- alarum",
		"alembic -- limbeck",
		"alguazil -- visier -- vizier",
		"allocate -- allow",
		"alloy -- ally",
		"alone -- lone",
		"ameer -- emir -- omrah",
		"amiable -- amicable",
		"an -- one",
		"ancient -- ensign",
		"announce -- annunciate",
		"ant -- emmet",
		"anthem -- antiphon",
		"antic -- antique",
		"appal -- pall",
		"appeal -- peal",
		"appear -- peer",
		"appraise -- appreciate",
		"appraise -- appreciate -- apprize",
		"apprentice -- prentice",
		"aptitude -- attitude",
		"arc -- arch",
		"armada -- army",
		"arquebus -- hackbut",
		"arrack -- rack -- raki",
		"asparagus -- spray -- sprig",
		"asphodel -- daffodil",
		"assay -- essay",
		"assemble -- assimilate",
		"assess -- assize",
		"assess -- cess",
		"assise -- size -- size",
		"astonish -- astound -- stun",
		"attach -- attack",
		"attaint -- taint",
		"attar -- otto",
		"attire -- tire -- tire",
		"auscultate -- scout",
		"bale -- ball",
		"balm -- balsam",
		"band -- bond",
		"banjo -- mandolin",
		"banjo -- mandoline",
		"bank -- bank -- bench",
		"barb -- bard",
		"barge -- bark",
		"base -- basis",
		"bashaw -- pasha",
		"baton -- batten",
		"bawd -- bold",
		"beadle -- bedell",
		"beaker -- pitcher",
		"beam -- boom",
		"beech -- book -- buck(wheat)",
		"beef -- cow",
		"beldam -- belladonna",
		"belly -- bellows",
		"benediction -- benison",
		"benison -- benediction",
		"bile -- boil",
		"blame -- blaspheme",
		"block -- plug",
		"boss -- botch",
		"bough -- bow",
		"boulevard -- bulwark",
		"bound -- bourn",
		"bower -- byre",
		"bowl -- bull",
		"box -- bush -- pyx",
		"brave -- bravo",
		"breve -- brief",
		"brother -- friar",
		"brown -- bruin",
		"buff -- buffalo",
		"cad -- cadet",
		"cadence -- chance",
		"cage -- cave",
		"cage -- coy",
		"caitiff -- captive",
		"caldron -- cauldron -- chaldron",
		"caliber -- caliver",
		"calumny -- challenge",
		"calx -- chalk",
		"camera -- chamber",
		"campaign -- champaign",
		"canal -- channel -- kennel",
		"cancel -- chancel",
		"cancer -- canker",
		"cannon -- canon",
		"cant -- chant",
		"cape -- chief",
		"capital -- cattle -- chattel",
		"capital -- cattle -- chattels",
		"capital -- chapiter",
		"captain -- chieftain",
		"caravan -- van",
		"card -- carte -- chart",
		"cargo -- cark -- charge",
		"cargo -- charge",
		"carmine -- crimson",
		"carnation -- coronation",
		"cart -- chariot",
		"case -- cash -- chase",
		"cask -- casque",
		"castigate -- chasten",
		"castle -- chateau",
		"catch -- chase",
		"catch -- ketch",
		"cavalier -- chevalier",
		"cavalry -- chivalry",
		"cell -- hall",
		"chair -- chaise",
		"chamois -- shammy",
		"cheat -- escheat",
		"check -- shah",
		"chest -- cist",
		"chicory -- succory",
		"chirurgeon -- surgeon",
		"chive -- cive",
		"choir -- chorus -- quire",
		"choler -- cholera",
		"chord -- cord",
		"chrism -- cream",
		"chuck -- shock -- shog",
		"church -- kirk",
		"cipher -- zero",
		"cithern -- gittern -- guitar -- kit",
		"clause -- close",
		"climate -- clime",
		"coffer -- coffin",
		"coign -- coin -- quoin",
		"coil -- collect -- cull",
		"cole -- kail",
		"collocate -- couch",
		"comfit -- confect",
		"command -- commend",
		"commander -- commodore",
		"complacent -- complaisant",
		"complete -- comply",
		"composite -- compost",
		"comprehend -- comprise",
		"compute -- count",
		"conduct -- conduit",
		"confound -- confuse",
		"construct -- construe",
		"convey -- convoy",
		"cool -- gelid",
		"copulate -- couple",
		"corn -- grain",
		"corn -- horn",
		"corral -- kraal",
		"corsair -- hussar",
		"costume -- custom",
		"cot -- cote",
		"coup -- crop",
		"coy -- quiet -- quit -- quite",
		"crape -- crisp",
		"cratch -- crib",
		"crate -- hurdle",
		"crease -- crest",
		"crevasse -- crevice",
		"crowd -- rote",
		"crypt -- grot",
		"cud -- quid",
		"cue -- queue",
		"curari -- wourali",
		"curricle -- curriculum",
		"curtle-axe -- cutlass",
		"cycle -- wheel",
		"dace -- dare -- dart",
		"dado -- die",
		"daft -- deft",
		"dainty -- dignity",
		"dais -- desk -- disc -- discus -- dish",
		"dale -- dell",
		"dam -- dame -- donna -- duenna",
		"dan -- domino -- don",
		"danger -- dominion",
		"dauphin -- dolphin",
		"daïs -- desk -- disc -- dish",
		"deal -- dole",
		"debt -- due",
		"deck -- thatch",
		"defeat -- defect",
		"defence -- fence",
		"defend -- fend",
		"delay -- dilate",
		"demesne -- domain",
		"dent -- dint",
		"deploy -- display -- splay",
		"deposit -- depot",
		"depot -- deposit",
		"describe -- descry",
		"desiderate -- desire",
		"despite -- spite",
		"deuce -- two",
		"devilish -- diabolic",
		"devilish -- diabolical",
		"diaper -- jasper",
		"dictum -- ditto",
		"dike -- ditch",
		"direct -- dress",
		"dispend -- spend",
		"disport -- sport",
		"distain -- stain",
		"distil -- still",
		"distress -- stress",
		"ditto -- dictum",
		"diurnal -- journal",
		"doge -- duke",
		"doit -- thwaite",
		"dominion -- dungeon",
		"down -- dune",
		"down -- town",
		"dragon -- dragoon",
		"drill -- thirl -- thrill",
		"dropsy -- hydropsy",
		"eatable -- edible",
		"elect -- élite",
		"elf -- oaf -- ouphe",
		"emerald -- smaragdus",
		"emerods -- hemorrhoids",
		"employ -- implicate -- imply",
		"endow -- endue -- indue",
		"engine -- gin",
		"ensample -- example -- sample",
		"ensign -- insignia",
		"entire -- integer",
		"envious -- invidious",
		"escape -- scape",
		"eschew -- shy",
		"escutcheon -- scutcheon",
		"especial -- special",
		"espy -- spy",
		"esquire -- squire",
		"establish -- stablish",
		"estate -- state -- status",
		"esteem -- estimate",
		"estop -- stop",
		"estreat -- extract",
		"etiquette -- ticket",
		"excoriate -- scourge",
		"exemplar -- sampler",
		"extraneous -- strange",
		"eyas -- nias",
		"fabric -- forge",
		"facility -- faculty",
		"fact -- feat",
		"faction -- fashion",
		"fade -- vade",
		"faldstool -- fauteuil",
		"fallow -- pale -- pallid",
		"fan -- van",
		"fancy -- fantasy -- phantasy",
		"farce -- force",
		"fardel -- furl",
		"fat -- vat",
		"fealty -- fidelity",
		"febrifuge -- feverfew",
		"fee -- feud -- fief",
		"feeble -- foible",
		"fell -- pell",
		"fester -- fistula",
		"fiasco -- flask",
		"fiddle -- viol",
		"field -- veldt",
		"fife -- peep -- pipe",
		"finch -- spink",
		"fine -- finite",
		"fitch -- vetch",
		"flag -- flake -- flaw",
		"flame -- phlegm",
		"flounce -- frounce",
		"flour -- flower",
		"flush -- flux",
		"foam -- spume",
		"font -- fount",
		"foremost -- prime",
		"forester -- foster",
		"fragile -- frail",
		"fro -- from",
		"fungus -- sponge",
		"furnish -- veneer",
		"gabble -- jabber",
		"gad -- ged",
		"gaffer -- grandfather",
		"gage -- wage",
		"gambado -- gambol",
		"game -- gammon",
		"gaol -- jail",
		"garb -- gear",
		"garner -- granary",
		"garth -- yard",
		"gay -- jay",
		"genie -- jinn",
		"genteel -- gentile -- gentle",
		"genteel -- gentile -- gentle -- jaunty",
		"genus -- kin",
		"germ -- germen",
		"gig -- jig",
		"gin -- juniper",
		"gird -- gride",
		"girdle -- girth",
		"glamour -- gramarye",
		"glamour -- grammar",
		"glib -- lib",
		"grade -- grece -- grise",
		"guarantee -- warranty",
		"guard -- ward",
		"guardian -- warden",
		"guest -- host",
		"guide -- guy",
		"guile -- wile",
		"guise -- wise",
		"gullet -- gully",
		"gust -- gusto",
		"hackle -- hatchel -- heckle",
		"hale -- whole",
		"hamper -- hanaper",
		"harangue -- rank -- ring -- rink",
		"hash -- hatch",
		"haulm -- shalm -- shawm",
		"hautboy -- oboe",
		"heap -- hope",
		"hemi- -- semi-",
		"hent -- hint",
		"history -- story",
		"hob -- hub",
		"hock -- hough",
		"hoop -- whoop",
		"hospital -- hostel -- hotel -- spital -- spittle",
		"human -- humane",
		"hyacinth -- jacinth",
		"hydra -- otter",
		"hyper- -- super-",
		"hypo- -- sub-",
		"illumine -- limn",
		"inapt -- inept",
		"inch -- ounce",
		"indict -- indite",
		"influence -- influenza",
		"innocuous -- innoxious",
		"insulate -- isolate",
		"insulation -- isolation",
		"invite -- vie",
		"invocate -- invoke",
		"iota -- jot",
		"jaggery -- sugar",
		"jealous -- zealous",
		"jet -- jut",
		"jetty -- jutty",
		"joint -- junta -- junto",
		"jointure -- juncture",
		"kin -- genus",
		"label -- lapel -- lappet",
		"lac -- lake",
		"lace -- lasso",
		"lair -- leaguer",
		"lake -- loch -- lough",
		"lance -- lanch -- launch",
		"lateen -- Latin",
		"leal -- legal -- loyal",
		"lection -- lesson",
		"lieu -- locus",
		"limb -- limbo",
		"lineal -- linear",
		"liqueur -- liquor",
		"list -- lust",
		"listen -- lurk",
		"llano -- plain -- plan -- plane",
		"load -- lode",
		"lobby -- lodge",
		"lobster -- locust",
		"locust -- lobster",
		"lorel -- losel",
		"lurch -- lurk",
		"madam -- madonna",
		"major -- mayor",
		"male -- masculine",
		"malediction -- malison",
		"mall -- maul",
		"mallow -- mauve",
		"mandate -- maundy",
		"maneuver -- manure",
		"mangle -- mangonel",
		"manure -- manœuvre",
		"march -- mark -- marque",
		"marge -- margent -- margin",
		"marish -- morass",
		"master -- mister",
		"maxim -- maximum",
		"mazer -- mazzard",
		"mean -- mesne -- mizen",
		"memoir -- memory",
		"mentor -- monitor",
		"metal -- mettle",
		"milk -- milt",
		"minim -- minimum",
		"minster -- monastery",
		"mint -- money",
		"mob -- mobile -- movable",
		"mode -- mood",
		"module -- mould",
		"mohair -- moire",
		"moment -- momentum -- movement",
		"monetary -- monitory",
		"monster -- muster",
		"morn -- morrow",
		"moslem -- mussulman",
		"mosquito -- musket",
		"mullion -- munnion",
		"musket -- mosquito",
		"naive -- native",
		"naked -- nude",
		"name -- noun",
		"natron -- nitre",
		"naught -- not -- nought",
		"nausea -- noise",
		"neat -- net",
		"newel -- noyau",
		"nouch -- ouch",
		"obedience -- obeisance",
		"octave -- utas",
		"of -- off",
		"onion -- union",
		"opera -- ure",
		"oration -- orison",
		"ordinance -- ordnance",
		"orpiment -- orpine",
		"osprey -- ossifrage",
		"outer -- utter",
		"overplus -- surplus",
		"pace -- pass",
		"paddle -- spatula",
		"paddock -- park",
		"paganism -- paynim",
		"pain -- pine",
		"paladin -- palatine",
		"palaver -- parable -- parabola -- parley -- parole",
		"palaver -- parable -- parle -- parole",
		"pale -- pawl -- pole",
		"palette -- pallet",
		"palsy -- paralysis",
		"pane -- pawn -- vane",
		"papa -- pope",
		"paper -- papyrus",
		"parade -- parry",
		"paradise -- parvis",
		"parcel -- particle",
		"paritory -- pellitory",
		"parson -- person",
		"pastel -- pastille",
		"pasty -- patty",
		"pate -- plate",
		"patron -- pattern",
		"pauper -- poor",
		"pause -- pose",
		"peak -- pick -- pike -- pique -- spike",
		"peck -- pick -- pitch",
		"peise -- poise",
		"pelisse -- pilch",
		"penance -- penitence",
		"peregrine -- pilgrim",
		"periwig -- peruke -- wig",
		"pestle -- pistil",
		"pewter -- spelter",
		"phantasm -- phantom",
		"piazza -- place",
		"piazza -- place -- plaza",
		"picket -- piquet",
		"piety -- pity",
		"pigment -- pimento",
		"pip -- pippin",
		"pistol -- pistole",
		"plaintiff -- plaintive",
		"plait -- pleat -- plight",
		"plateau -- platter",
		"plum -- prune",
		"poesy -- posy",
		"poignant -- pungent",
		"point -- punt",
		"poison -- potion",
		"poke -- pouch",
		"pomade -- pomatum -- pommade",
		"pomp -- pump",
		"pond -- pound",
		"porch -- portico",
		"posse -- power",
		"potent -- puissant",
		"poult -- pullet",
		"pounce -- pumice",
		"pounce -- punch",
		"pound -- pun",
		"praise -- price",
		"preach -- predicate",
		"premier -- primero",
		"presbyter -- priest",
		"private -- privy",
		"probe -- proof",
		"proctor -- procurator",
		"profile -- purl",
		"prolong -- purloin",
		"propose -- purpose",
		"prosecute -- pursue",
		"provide -- purvey",
		"provident -- prudent",
		"proviso -- purview",
		"puisne -- puny",
		"punch -- punish",
		"quadroon -- quartern",
		"quean -- queen",
		"quiet -- quit -- quite -- coy",
		"quinsy -- squinancy",
		"race -- radish -- radix -- root -- wort",
		"raceme -- raisin",
		"rack -- wrack -- wreck",
		"radius -- ray",
		"raid -- road",
		"rail -- rally",
		"raise -- rear",
		"ramp -- romp",
		"ransom -- redemption",
		"rapine -- raven -- ravine",
		"rase -- raze",
		"ratio -- ration -- reason",
		"rayah -- ryot",
		"real -- regal -- royal",
		"rear-guard -- rear-ward",
		"reave -- rob",
		"recognisance -- reconnaissance",
		"regard -- reward",
		"relic -- relique",
		"renegade -- runagate",
		"renew -- renovate",
		"reprieve -- reprove",
		"residue -- residuum",
		"respect -- respite",
		"restrain -- restrict",
		"revenge -- revindicate",
		"rhomb -- rhombus -- rumb",
		"ridge -- rig",
		"robber -- rover",
		"rod -- rood",
		"rondeau -- roundel",
		"rote -- rout -- route -- rut",
		"rotund -- round",
		"rouse -- row",
		"rover -- robber",
		"sac -- sack",
		"sacristan -- sexton",
		"saddle -- sell -- settle",
		"saga -- saw",
		"saliva -- slime",
		"sassafras -- saxifrage",
		"sauce -- souse",
		"scabby -- shabby",
		"scale -- shale",
		"scandal -- slander",
		"scar -- scaur -- share",
		"scaramouch -- scrimmage -- skirmish",
		"scarf -- scrap -- scrip",
		"scatter -- shatter",
		"school -- scull -- shoal",
		"scot(free) -- shot",
		"scour -- scur",
		"screed -- shred",
		"screen -- shriek",
		"screw -- shrew",
		"scuffle -- shuffle",
		"scuttle -- skillet",
		"search -- shark",
		"sect -- sept -- set -- suit -- suite",
		"secure -- sicker -- siker -- sure",
		"secure -- sure",
		"seignior -- senior -- señor -- signor -- sir -- sire",
		"sennet -- signet",
		"separate -- sever",
		"sequin -- sicca",
		"sergeant -- serjeant -- servant",
		"sergeant -- servant",
		"shade -- shed",
		"shallop -- sloop",
		"sheave -- shive",
		"sherbet -- shrub -- syrup",
		"ship -- skiff",
		"shirt -- skirt",
		"shiver -- skewer",
		"sine -- sinus",
		"slabber -- slaver",
		"slate -- éclat",
		"sleight -- sloid",
		"sleuth -- slot",
		"slobber -- slubber",
		"snivel -- snuffle",
		"snub -- snuff",
		"soil -- sole -- sole",
		"soprano -- sovereign",
		"sough -- surf",
		"soup -- sup",
		"spade -- spade",
		"spark -- spry",
		"species -- spice",
		"spell -- spill",
		"spirit -- spright -- sprite",
		"spoor -- spur",
		"spout -- sprout",
		"sprit -- sprout",
		"squall -- squeal",
		"square -- squire",
		"stack -- stake -- steak -- stock",
		"staff -- stave",
		"stank -- tank",
		"steer -- Taurus",
		"stew -- stove",
		"stock -- tuck",
		"strait -- strict",
		"strap -- strop",
		"superficies -- surface",
		"supersede -- surcease",
		"supervisor -- surveyor",
		"suppliant -- supplicant",
		"sweep -- swoop",
		"tabor -- tambour",
		"tache -- tack",
		"tamper -- temper",
		"tape -- tippet",
		"tar -- tarpauling",
		"task -- tax",
		"tassel -- tercel",
		"taunt -- tempt -- tent",
		"taw -- tee",
		"tawny -- tenny",
		"tease -- tose",
		"teat -- tit",
		"teind -- tenth -- tithe",
		"tend -- tender",
		"tense -- toise",
		"thread -- thrid",
		"tine -- tooth",
		"title -- tittle",
		"to -- too",
		"ton -- tun",
		"tone -- tune",
		"touch -- tuck",
		"tour -- turn",
		"tow -- tug",
		"track -- trick",
		"tract -- trait",
		"tradition -- treason",
		"travail -- travel",
		"treble -- triple",
		"trifle -- truffle",
		"tripod -- trivet",
		"triumph -- trump",
		"troth -- truth",
		"tuck -- tug",
		"tulip -- turban",
		"tweak -- twitch",
		"two -- deuce",
		"umbel -- umbrella",
		"unit -- unity",
		"utter -- outer",
		"vair -- various",
		"valet -- varlet",
		"vanguard -- vaward",
		"vast -- waste",
		"veal -- wether",
		"veneer -- furnish",
		"venew -- veney -- venue",
		"verb -- word",
		"verbena -- vervain",
		"vermeil -- vermillion",
		"vertex -- vortex",
		"viaticum -- voyage",
		"viper -- wivern -- wyvern",
		"visor -- vizard",
		"vocal -- vowel",
		"waggon -- wagon -- wain",
		"wale -- weal",
		"wallet -- wattle",
		"warble -- whirl",
		"weald -- wold",
		"weet -- wit",
		"whit -- wight",
		"yap -- yelp",
		"zero -- cipher",
	}
)

type doubletRepository struct {
}

func NewDoubletRepository() repository.DoubletRepository {
	return &doubletRepository{}
}

func (*doubletRepository) Get() []string {
	return DoubletVariants
}
